version: '3'
services:
        webclient:
                image: "srswinde/indi_webclient"
                ports: 
                        - "3000:3000"
                environment:
                        - INDISERVER=localhost
                
                
                command:
                        ["/webclient/websocketd", "--address", "0.0.0.0", "--port", "3000", "--devconsole", "/webclient/webclient", "indiserver"]
                

        nginx-server:
                image: "nginx"
                ports:
                        - "4001:80"
                volumes:
                        - "./www:/usr/share/nginx/html"
                

        indiserver:
                # stable tag was a version with no error
                # message if vatttel was not communicating
                # We should move the vatttel_not_on
                # to stable when we are sure the
                # update fix doesn't cause any issues
                # -Scott May 2019
                 
                
                #                image:  "srswinde/indihex:stable"
                image: "srswinde/indiserver"
                ports:
                        - "7624:7624"
                command: "/usr/bin/indiserver -v -r 0 /src/main.py"
                volumes:
                        - "//C/Users/srswi/git-clones/pyINDI/src:/src"


                
               
#        indidriver:
#                image: "srswinde/indidrivers"
#                ports:
#                        - "7624:7624"
#                network_mode: "host"
#                command:
#                        /usr/bin/indiserver  -vvv /driverbin/tcs-indi
#                        #/usr/bin/indiserver  -vvv /driverbin/tcs-indi /driverbin/dome-indi /driverbin/focus-indi /driverbin/snooper

#        browser:
#                image: "srswinde/firefox"
#                volumes:
#                        - "/tmp/.X11-unix:/tmp/.X11-unix"
#                environment:
#                        - DISPLAY=unix$DISPLAY
#                command:
#                        /usr/bin/chromium-browser /usr/bin/chromium-browser --no-sandbox --app=http://localhost/tcs.html
#                network_mode: "host"
#

#        xephem:
#                image: "srswinde/xephem"
#                volumes:
#                        - "${HOME}/.xephem:/home/developer/.xephem"
#                        - "/tmp/.X11-unix:/tmp/.X11-unix"
#                environment:
#                        - DISPLAY=$DISPLAY
#                        - HOME=/home/developer
#                network_mode: "host"
#                #                depends_on:
#                #                        - browser
#
