# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

name: Python Tests

on:
  push:
    branches:
    - master 
  pull_request:
    branches: 
    - master

jobs:

  matrix_tests:
    on:
      workflow_run:
        workflows: [docker]
        types:
          - completed
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-ver: [8, 9]
        tox-env: [cov, astropylts, astropydev]
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.${{ matrix.python-ver }} with tox environment ${{ matrix.tox-env }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.${{ matrix.python-ver }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy tox
    - name: Run indiserver test server in container
      run: docker run -d --rm -p 7624:7624 -w="/scripts" mmtobservatory/pyindi:latest
    - name: Test with tox
      run: |
        tox -e py3${{ matrix.python-ver }}-${{ matrix.tox-env }}
    - name: Upload coverage to codecov
      if: matrix.tox-env == 'cov' && matrix.python-ver == '8'
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV }}
        file: ./coverage.xml
        fail_ci_if_error: true

  doc_test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python to test links in docs with sphinx
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Build and check docs using tox
      run: |
        tox -e linkcheck
  build_docs:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python to build docs with sphinx
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Build docs using tox
      run: |
        tox -e build_docs
  codestyle:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Python codestyle check
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Check codestyle using tox
      run: |
        tox -e codestyle